config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  # Images implementation
  mount Attachinary::Engine => "/attachinary"

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'pages#home'

  devise_for :users, path_prefix: 'd', :controllers => { :registrations => :devise_registrations, omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:show]

  resources :events, except: [:index, :show]

  resources :events, only: [:show] do
    resources :registrations, only: [:create, :destroy, :update]
  end

  get '/events/', to: 'events#search', as: 'search'
  get '/save_data/', to: 'events#search'
  get '/events/:id/users/', to: 'events#users', as: 'event_users'
  get '/my_events/', to: 'events#my_events', as: 'user_events'
  get "/login_signup/", to: "pages#login_signup", as: "login_signup"
  get '/home_create/', to: 'pages#home_create', as: 'home_create'
  get '/home_search/', to: 'pages#home_search', as: 'home_search'

  get '/new/:number', to: "events#cool_form", as: 'cool_form'
  get '/events/:id/edit/:number', to: "events#cool_form_edit", as: 'cool_form_edit'


end

app/views/shared/_burger_dropdown.html.erb
<!-- This file is not user anywhere? Do we need it? -->

<!-- <ul id="nav">
  <li><a href="#">Home</a></li>
  <li><a href="#">About</a></li>
  <li><a href="#">Contact</a></li>
</ul>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script type="text/javascript">
  $("#nav").addClass("js").before('<div id="menu">&#9776;</div>');
  $("#menu").click(function(){
    $("#nav").toggle();
  });
  $(window).resize(function(){
    if(window.innerWidth > 768) {
      $("#nav").removeAttr("style");
    }
  });
</script> -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert" style="z-index: 10000;position: absolute; width: 100%; <%= "background-color: #6989F9;" if controller.action_name == "cool_form" || controller.action_name == "cool_form_edit" %>">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <% if notice.is_a?(Hash) %>
      <% notice.each do |key, messages| %>
        <% messages.each do |message| %>
            <div> <%= key %>: <%= message %> </div>
        <% end %>
      <% end %>
    <% else %>
      <%= notice %>
    <% end %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert" style="z-index: 10000;position: absolute; width: 100%;">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top" data-spy="affix" data-offset-top="50" style="width: 100vw;">

  <!-- TOP NAV -->
  <div id="navbar-top" class="navbar-wagon">
    <%= render 'shared/navbar_top' %>
  </div>

  <!-- BOTTOM NAV -->
  <div id="navbar-bottom" class="navbar-wagon">
    <%= render 'shared/navbar_bottom' %>
  </div>

</div>

app/views/shared/_navbar_bottom.html.erb
<!-- Right Navigation -->
<!-- LARGER SCREENS -->
<div class="navbar-wagon-bottom">

  <!-- Search -->

<% if current_page?(controller: 'events', action: 'search') %>
    <%= link_to events_path, class: "nav-button nav-button-text navbar-wagon-item-bottom navbar-wagon-link active-icon" do %>
        <span class="nav-icon fa fa-search"></span><br>
        <span class="nav-button-text">Search</span>
        <% end %>
      <% else %>
      <%= link_to events_path, class: "nav-button nav-button-text navbar-wagon-item-bottom navbar-wagon-link" do %>
        <span class="nav-icon fa fa-search"></span><br>
        <span class="nav-button-text">Search</span>
      <% end %>
    <% end %>


  <!-- Add Event -->
    <%= link_to cool_form_path(1), class: "nav-button nav-button-text navbar-wagon-item-bottom navbar-wagon-link" do %>
    <span class="nav-icon fa fa-plus-circle"></span><br>
      <span class="nav-button-text">Add Event</span>
    <% end %>

  <!-- My Events -->
      <% if current_page?(controller: 'events', action: 'my_events') %>
          <%= link_to user_events_path, class: "nav-button nav-button-text navbar-wagon-item-bottom navbar-wagon-link active-icon" do %>
          <span class="nav-icon fa fa-calendar-check-o"></span><br>
          <span class="nav-button-text">My Events</span>
      <% end %>
      <% else %>
        <%= link_to user_events_path, class: "nav-button nav-button-text navbar-wagon-item-bottom navbar-wagon-link" do %>
        <span class="nav-icon fa fa-calendar-check-o"></span><br>
        <span class="nav-button-text">My Events</span>
      <% end %>
    <% end %>

</div>

app/views/shared/_navbar_top.html.erb
<!-- Logo -->
    <a href="/" class="navbar-wagon-brand">
      <%= image_tag "Logo_little.png", {id: "logo"} %>
    </a>

    <!-- Search form, hidden on phone screens -->
<!--     <div class="hidden-xs">
      <form action="" class="navbar-wagon-search">
        <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
        <button type="submit" class="navbar-wagon-search-btn">
          <i class="fa fa-search"></i>
        </button>
      </form>
    </div> -->

    <!-- DROPDOWN MENU -->

    <% if user_signed_in? %>

      <!-- USER -->

      <div class="navbar-wagon-item no-padding">

        <div class="dropdown-toggle" data-toggle="dropdown">
          <!-- <i class="fa fa-user-circle-o fa-2x dropdown-button"></i> -->

          <img src="<%= avatar_for_user(current_user) %>" alt="" class="avatar">

          <i id="caret" class="fa fa-caret-down dropdown-button"></i>
        </div>

        <ul id="dropdown" class="dropdown dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "My Profile", user_path(current_user), class: "" %>
          </li>
          <li>
            <%= link_to "Log Out", destroy_user_session_path, class: "", method: :delete %>
          </li>
        </ul>
      </div>

    <% else %>

      <!-- NON USER -->
      <div class="navbar-wagon-item no-padding">
        <div class="dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-bars fa-2x dropdown-button"></i>
        </div>
        <ul id="dropdown" class="dropdown dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "Log In", new_user_session_path, class: "" %>
          </li>
          <li>
            <%= link_to "Sign Up", new_user_registration_path, class: "" %>
          </li>
        </ul>
      </div>

    <% end %>