config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  # Images implementation
  mount Attachinary::Engine => "/attachinary"

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'pages#home'

  devise_for :users, path_prefix: 'd', :controllers => { :registrations => :devise_registrations, omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:show]

  resources :events, except: [:index, :show]

  resources :events, only: [:show] do
    resources :registrations, only: [:create, :destroy, :update]
  end

  get '/events/', to: 'events#search', as: 'search'
  get '/save_data/', to: 'events#search'
  get '/events/:id/users/', to: 'events#users', as: 'event_users'
  get '/my_events/', to: 'events#my_events', as: 'user_events'
  get "/login_signup/", to: "pages#login_signup", as: "login_signup"
  get '/home_create/', to: 'pages#home_create', as: 'home_create'
  get '/home_search/', to: 'pages#home_search', as: 'home_search'

  get '/new/:number', to: "events#cool_form", as: 'cool_form'
  get '/events/:id/edit/:number', to: "events#cool_form_edit", as: 'cool_form_edit'


end

app/models/event.rb
class Event < ApplicationRecord

  TAGS = ['Animals', 'Children', 'Community', 'Technology', 'Crisis Support', 'Education', 'Environment', 'Homeless', 'Health', 'Refugees', 'LGBT', 'Disabled', 'Seniors', 'Sports', 'Women']
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  belongs_to :organizer, class_name: "User", foreign_key: "organizer_id"

  has_many :registrations, dependent: :destroy
  has_many :participants, through: :registrations

  # Photo implementation
  has_attachments :photos, maximum: 6

  validates :organizer_id, presence: true, numericality: true
  validates :name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :address, presence: true
  validates :capacity, presence: true, numericality: true
  validates :description, presence: true
  validates :tags, presence: true

  after_update :send_update_email, if: :start_time_changed? || :finish_time_changed?
  after_update :update_registrations, if: :start_time_changed? || :finish_time_changed?


  scope :today, -> { where('start_time BETWEEN ? AND ?', Time.now, Date.tomorrow.beginning_of_day.to_time).order(start_time: :asc) }
  scope :tomorrow, -> { where('start_time BETWEEN ? AND ?', Date.tomorrow.beginning_of_day.to_time, Date.tomorrow.end_of_day.to_time).order(start_time: :asc) }
  scope :this_week, -> { where('start_time BETWEEN ? AND ?', Date.tomorrow.end_of_day.to_time, Date.today.end_of_week.end_of_day.to_time).order(start_time: :asc) }
  scope :next_week, -> { where('start_time BETWEEN ? AND ?', Date.today.end_of_week.end_of_day.to_time, Date.today.end_of_week.next_week.end_of_week.to_time).order(start_time: :asc) }
  scope :later, -> { where('start_time > ?', Date.today.end_of_week.next_week.end_of_week.to_time).order(start_time: :asc) }
  scope :including_tags, ->(tags_list) { where("tags @> ?", "{#{tags_list.join(",")}}") }
  scope :uncomplete, -> {where('capacity > ?', participants.count)}

  def spots_left
    self.capacity - self.participants.count
  end

  def start_day
    start_time.to_date
  end

  private

  def send_update_email
    EventMailer.update(self.id).deliver_later
  end

  def update_registrations
    self.registrations.each do |registration|
      registration.update_sms_time
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :search, :new, :create, :cool_form]


  skip_after_action :verify_authorized, only: [:show, :search]
  after_action :verify_policy_scoped, only: [:search], unless: :skip_pundit?

  before_action :set_event, only: [:show, :edit, :update, :destroy, :users]

  def search
    @event = Event.new
    session[:search_results] = params[:address]
    @events = policy_scope(Event)

    unless params[:event].nil? || params[:event][:tags].blank?
      tags_list = params[:event][:tags].select { |i| i.present? }
      @events = @events.including_tags(tags_list)
    end

    @address = params[:event][:address] if params[:event]

    unless params[:event].nil? || @address.blank?
      # What is that?
      @events = @events.where("address ILIKE ?", "%#{@address}%")
    end
  end


  def my_events
    @user = current_user
    authorize @user

    @past_events_attended = past_events_attendee(@user)
    @current_events_attended = current_events_attendee(@user)
    @past_events_managed = past_events_manager(@user)
    @current_events_managed = current_events_manager(@user)
  end


  def users
    @event_users = @event.participants.all
  end

  def show
    @event_is_past = @event.end_time < DateTime.now ? true : false
    if current_user
      @organizer_is_user = @event.organizer_id == current_user.id ? true : false
    end
    @spots_left = @event.capacity - @event.participants.count
    @spots_left = 0 if @spots_left < 0
    @tags_list = @event.tags
    @participants = @event.participants

    @hash = Gmaps4rails.build_markers(@event) do |event, marker|
      if event.latitude
        marker.lat event.latitude
        marker.lng event.longitude
      else
        marker.lat '29.9792345'
        marker.lng '31.1320132'
      end
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end

  end

  def new
    @event = Event.new
    authorize @event
    session[:search_results] = params[:address]
    @events = policy_scope(Event)
    @address = params[:event][:address] if params[:event]
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.start_time = DateTime.parse(params[:event][:start_day] + ' ' + params[:event][:start_time])
    @event.end_time = DateTime.parse(params[:event][:end_day] + ' ' + params[:event][:end_time])

    authorize @event

    if current_user
      @event.organizer_id = current_user.id
      if @event.save
        redirect_to @event, notice: 'Event was successfully created.'
      else
        redirect_to cool_form_path(1), notice: @event.errors.messages
      end
    else
      @event.organizer_id = 0
      user = User.find_by(id: 0)
      user = User.create(id: 0, first_name: "placehold", last_name: "placehold", email: "testaa@test.com", password: "testtest" ) unless user
      if @event.save
        cookies[:event_id] = @event.id
        cookies[:participant] = "false"
        redirect_to new_user_session_path
      else
        redirect_to cool_form_path(1), notice: @event.errors.messages
      end
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to user_events_path, notice: 'Event was successfully destroyed.'
  end


  def cool_form
    number = params[:number]
    case number
    when "1"
      @event = Event.new
      @event.start_time = 2.days.from_now
      @event.end_time = 2.days.from_now
      authorize @event
    when "2"
      fill_cool_form
      @event.start_time = DateTime.parse(params[:event][:start_day] + ' ' + params[:event][:start_time])
      @event.end_time = DateTime.parse(params[:event][:end_day] + ' ' + params[:event][:end_time])
    when "3"
      fill_cool_form
      @event.start_time = DateTime.parse(params[:event][:start_day] + ' ' + params[:event][:start_time])
      @event.end_time = DateTime.parse(params[:event][:end_day] + ' ' + params[:event][:end_time])
    end
  end

  def cool_form_edit
    number = params[:number]
    case number
    when "1"
      set_event
    when "2"
      fill_cool_edit_form
      @event.start_time = DateTime.parse(params[:event][:start_day] + ' ' + params[:event][:start_time])
      @event.end_time = DateTime.parse(params[:event][:end_day] + ' ' + params[:event][:end_time])
    when "3"
      set_event
      @event.start_time = DateTime.parse(params[:event][:start_day] + ' ' + params[:event][:start_time])
      @event.end_time = DateTime.parse(params[:event][:end_day] + ' ' + params[:event][:end_time])
      begin
        event_params
        unless @event.update(event_params)
          respond_to do |format|
            flash.now[:error] = 'It did not work'
            format.js {render inline: "location.reload();", notice: @event.errors.messages }
          end
        end
      rescue ActionController::ParameterMissing
      end
    when "4"
      fill_cool_edit_form
      redirect_to @event, notice: 'Event was successfully updated.'
    end
  end

  private

  def fill_cool_form
    @event = Event.new(event_params)
    authorize @event
  end

  def fill_cool_edit_form
    set_event
    unless @event.update(event_params)
      respond_to do |format|
        flash.now[:error] = 'It did not work'
        format.js {render inline: "location.reload();", notice: @event.errors.messages }
      end
    end
  end

  def set_event
    @event = Event.find(params[:id])
    authorize @event
  end

  def event_params
    params.require(:event).permit(:name, :organization, :start_time, :end_time, :address, :capacity, :description, :source_event_id, photos: [], tags: [])
  end

  def past_events_manager(user)
    user.events.where("end_time < ?", DateTime.now)
  end

  def current_events_manager(user)
    user.events.where("end_time > ?", DateTime.now)
  end

  def past_events_attendee(user)
    user.events_as_participant.where("end_time < ?", DateTime.now)
  end

  def current_events_attendee(user)
    user.events_as_participant.where("end_time > ?", DateTime.now)
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_cool_form_edit_partial_3.html.erb
<% content_for :full_page do %>


<%= render 'shared/flashes' %>

<div class="form-create">
<div class="form-signup">

  <div class="row">
    <div class="col-xs-12">
        <div class="close-form">
            <%= link_to event_path do %>
            <i class="fa fa-times" aria-hidden="true"></i>
            <% end %>
        </div>


      </div>

<!--       <div class="row"> -->
        <div class="sign-up-content">
        <div class="col-xs-12">
        <div class="sign-for-free">
          <h3>Edit your event</h3>

        </div>
        </div>
        <div class="col-xs-12">
        <div class="row">


          <div class="fill-form">

<div class=" col-xs-12">
<div class="row">
<div class="numbers-form">
<%= link_to "1", cool_form_edit_path(@event.id, 1), class: "numberCircle-others col-xs-4" %>
<%= link_to "2", cool_form_edit_path(@event.id, 2), class: "numberCircle-others col-xs-4" %>
<div class="numberCircle col-xs-4">3</div>
</div>
</div>




<div class="simple-form-for">
    <%= simple_form_for(@event, url: cool_form_edit_path(@event.id, 4), method: :get) do |f| %>
      <%= f.error_notification %>
      <% event = @event %>
            <div class="form-inputs">
            <div class="hidden-fields">

            <div class="input-group login-form">

            <%= f.input :name, placeholder: "Event Name",:label => false, input_html: { value: params[:name] || event.name,   class: 'form-control btn-lg btn-login' } %>
            </div>
            <div class="input-group login-form">
        <%= f.input :organization, placeholder: "My organization", :label => false, input_html: { value: params[:organization] || event.organization, class: 'form-control btn-lg btn-login' }  %>
        </div>
        <div style="display: none;">
        <div class="row">
            <div class="col-xs-6">
            <div class="input-group login-form">
            <%= f.date_field :start_day, :label => false, value: @event.start_time.strftime('%Y-%m-%d'), as: :hidden,  class: 'form-control btn-lg btn-login blue-time'  %>
           </div>
            </div>
            <div class="col-xs-6">
            <div class="input-group login-form">
             <%= f.time_field :start_day, :label => false, value: @event.start_time.strftime('%Y-%m-%d'), class: 'form-control btn-lg btn-login'  %>
        <%#= f.time_field :start_time, input_html: { value: params[:start_time] || event.start_time}  %>
            </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6">
            <div class="input-group login-form">
            <%= f.date_field :start_day, :label => false, value: @event.start_time.strftime('%Y-%m-%d'), class: 'form-control btn-lg btn-login'  %>
            </div>
            </div>
            <div class="col-xs-6">
            <div class="input-group login-form">
            <%= f.time_field :end_time, :label => false, value: @event.end_time.strftime('%H:%M'), class: 'form-control btn-lg btn-login'  %>
            </div>
            </div>
        </div>
        </div>

        <div class="input-group login-form">
        <%= f.input :address, placeholder: "Street, City, ZIP", :label => false, input_html: { value: @address || params[:address] || event.address, class: 'form-control btn-lg btn-login' }  %>
        </div>

        <div class="input-group login-form">

        <%= f.input :description, :label => false, placeholder: "What kind of help do you need?", input_html: { value: params[:description] || event.description, class: 'form-control btn-lg btn-login'  } %>
        </div>
        <div class="input-group login-form">

        <%= f.input :capacity, placeholder: "People required", :label => false, input_html: { value: params[:capacity] || event.capacity}  %>
        </div>
        </div>




<div class="login-form">
          <span class="input-group-addon btn-add-event-categories" id="basic-addon1">
            <i class="fa fa-filter" aria-hidden="true"></i> Categories
          </span>
          <div class="categories">
    <!--       <%= f.input :tags, :label => false, checked: (params[:event][:tags] if params[:event]), include_blank: false, as: :check_boxes, collection: Event::TAGS, class: 'check_boxes_submit', input_html: { value: params[:tags] || event.tags } %>
 -->
            <div class="form-group check_boxes required event_tags">
              <input type="hidden" name="event[tags][]" value="">
              <div class="row">
                <% Event::TAGS.each_with_index do |tag, i| %>
                  <div class="col-xs-5 col-xs-offset-1">
                    <span class="checkbox">
                      <label for="<%= "event_tags_#{tag.parameterize}" %>">
                        <input value="<%= tag %>" class="check_boxes required" type="checkbox" name="event[tags][]" id="<%= "event_tags_#{tag.parameterize}" %>">
                        <%= tag %>
                      </label>
                    </span>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>





        <div class="input-group login-form image-field">

        <%= f.input :photos, as: :attachinary, :label => false, class: 'form-control-file text-success font-weight-bold', input_html: { value: params[:photos] || event.photos }  %>
        </div>

        <div class="input-group login-form">

        <%= f.input :source_event_id, as: :hidden, :label => false, input_html: { value: params[:source_event_id], class: 'form-control btn-lg btn-login'  }  %>

      </div>



      <div class="form-actions">
        <%= f.button :submit, value: "Edit mission", data: {disable_with: "Loading..."}, class: "form-control btn-lg btn-next-step" %>
      </div>
    <% end %>

  </div>

      </div>
        </div>
        </div>
    <!--   </div> -->

            </div>

        </div>
      </div>

</div>

</div>
</div>

<% end %>

app/views/events/_current_event_attending_card.html.erb
<% if event.photos? %>
  <% main_photo = event.photos.first.path %>
<% else %>
  <% main_photo = image_path('teamwork.jpg') %>
<% end %>

<%= link_to(event, class: "link-no-style") do %>
<div class="event-card-container">
  <div class="event-card-image" style='background-image: linear-gradient(rgba(60,95,120,0.3), rgba(60,95,120,0.2)), url("<%= cl_image_path main_photo, height: 300, width: 600, crop: :fill, radius: 4; %>")'>

  </div>

  <div class="event-badge-attended">
      ATTENDING
  </div>

  <div class="event-card-tab">
      <h3><%= pluralize((event.end_time - DateTime.now).to_i/60/60/24, 'day', 'days') %></h3>
      <p>left</p>
  </div>

  <div class="event-card-data">

    <div class="event-card-caption">
      <h3><%= event.name %></h3>
    </div>

    <div class="event-card-address-row">
      <div class="event-card-address-icon">
        <i class="fa fa-home"></i>
      </div>
      <div class="event-card-address">
        <%= event.address %>
      </div>
    </div>

    <div class="event-card-time-row">
     <div class="event-card-time-icon">
        <i class="fa fa-clock-o"></i>
      </div>
      <div class="event-card-time">
        <%= event.start_time.strftime('%d/%m/%Y %H:%M') %>
      </div>
    </div>
  </div>

  <div class="event-card-separator"></div>

<!-- CARD FOOTER -->
<div class="event-card-footer">
    <%= link_to event_users_path(event) do %>
        <% @counter = 0 %>
        <% event.participants.first(3).each do |par| %>
        <% if par.photo %>
          <% @counter = @counter + 1 %>
          <%= cl_image_tag par.photo.path, class: "avatar-mini" %>
        <% end %>
      <% end %>
    <% end %>

    <div class="event-card-remainder">
      + <%= event.participants.count - @counter %> ARE GOING
    </div>

    <div class="share-event-button-default js-share" data-href="http://volunteasy.co<%= event_path(event) %>" data-content="Checkout this amazing event">
      <i class='fa fa-share-square-o'></i>
    </div>


</div>

</div><!-- CLOSE EVENT CARD -->
<% end %>

app/views/events/_event.html.erb
<% if event.photos? %>
  <% main_photo = event.photos.first.path %>
<% else %>
  <% main_photo = image_path('teamwork.jpg') %>
<% end %>

<%= link_to(event, class: "link-no-style") do %>
<div class="event-card-container">
  <div class="event-card-image" style='background-image: linear-gradient(rgba(60,95,120,0.3), rgba(60,95,120,0.2)), url("<%= cl_image_path main_photo, height: 300, width: 600, crop: :fill, radius: 4; %>")'>

  </div>

  <div class="event-card-tab">
      <h3><%= pluralize((event.end_time - DateTime.now).to_i/60/60/24, 'day', 'days') %></h3>
      <p>left</p>
  </div>

  <div class="event-card-data">

    <div class="event-card-caption">
      <h3><%= event.name %></h3>
    </div>

    <div class="event-card-address-row">
      <div class="event-card-address-icon">
        <i class="fa fa-home"></i>
      </div>
      <div class="event-card-address">
        <%= event.address %>
      </div>
    </div>

    <div class="event-card-time-row">
     <div class="event-card-time-icon">
        <i class="fa fa-clock-o"></i>
      </div>
      <div class="event-card-time">
        <%= event.start_time.strftime('%d/%m/%Y %H:%M') %>
      </div>
    </div>
  </div>



  <div class="event-card-separator"></div>



<!-- CARD FOOTER -->
<div class="event-card-footer">

    <%= link_to event_users_path(event) do %>
        <% @counter = 0 %>
        <% event.participants.first(3).each do |par| %>
        <% if par.photo %>
          <% @counter = @counter + 1 %>
          <%= cl_image_tag par.photo.path, class: "avatar-mini" %>
        <% end %>
      <% end %>
    <% end %>

    <div class="event-card-remainder">
      + <%= event.participants.count - @counter %> ARE GOING
    </div>

    <div class="share-event-button-default js-share" data-href="http://volunteasy.co<%= event_path(event) %>" data-content="Checkout this amazing event">
      <i class='fa fa-share-square-o'></i>
    </div>
</div>

</div><!-- CLOSE EVENT CARD -->
<% end %>

app/views/events/cool_form.html.erb
<% if params[:number] == "1" %>
  <%= render "form_partial_1", locals: {event: @event} %>
<% elsif params[:number] == "2" %>
  <%= render "form_partial_2", locals: {event: @event} %>
<% elsif params[:number] == "3" %>
  <%= render "form_partial_3", locals: {event: @event} %>
<% end %>

app/views/events/new.html.erb
<div class="wrapper">
  <div class="container">
    <div class="col-xs-12 col-sm-8 col-md-4">
      <div class="form-heading">
        <h2>Create a Mission!</h2>
        <h3>Find passionate people for your project</h3>
      </div>
      <%= render 'form', event: @event %>

    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3">
    <div class="event-show-card">
      <h2 class='text-center'> <%= @event.name %> </h2>

      <% @event.photos.each_with_index do |photo, index| %>
        <% if index == 0 %>
          <a rel="gallery-1" href="<%= cl_image_path photo.path %>" class="swipebox" title="<%= @event.name %>">
            <img src="<%= cl_image_path photo.path %>" alt="image" style="width: 100%; max-height: 300px; border-radius: 4px;">
          </a>
        <% else %>
          <a rel="gallery-1" href="<%= cl_image_path photo.path %>" class="swipebox hidden" title="<%= @event.name %>">
            <img src="<%= cl_image_path photo.path %>" alt="image" style="width: 100px; max-height: 300px; border-radius: 4px;">
          </a>
        <% end %>
      <% end %>
      <% if @event.photos.empty? && current_user == @event.organizer %>
        <%= link_to "Events with photos fare better, add some photos now?", cool_form_edit_path(@event.id, 3) %>
      <% end %>
      <% if @event.photos.count > 1 %>
          <p class="text-center">image 1 of <%= @event.photos.count %></p>
      <% end %>

      <!-- Time of event -->

      <% if @event_is_past %>
        <h3> When was it? </h3>
      <% else %>
        <h3> When is it? </h3>
      <% end %>
      <p>
        <strong>Begins:</strong> <%= @event.start_time.strftime('%d/%m/%Y') %> <%= @event.start_time.strftime("at %I:%M%p") %>
      </p>
      <p>
        <strong>Ends:</strong> <%= @event.end_time.strftime('%d/%m/%Y') %> <%= @event.end_time.strftime("at %I:%M%p") %>
      </p>

      <!-- Who goes to the event -->

      <% if @event_is_past %>
        <h3> Who went? </h3>
      <% else %>
        <h3> Who is coming? </h3>
      <% end %>
      <div class="participants">
        <% @participants.first(3).each do |par| %>
          <div class="participant">
          <% if par.photo %>
            <%= link_to user_path(par) do %>
              <%= cl_image_tag par.photo.path, crop: :fill, class: "participant-img" %>
            <% end %>
          <% else %>
            <%= link_to user_path(par) do %>
              <%= image_tag("no-img.png", class: "participant-img") %>
            <% end %>
          <% end %>
          <p> <%= par.first_name %> </p>
          </div>
        <% end %>

      </div>
      <%= link_to "see all", event_users_path(@event)  %>
      <br>
      <br>
      <!-- Spots left in the event -->

      <div class="spots-left">
        <p>
        Only <%= @spots_left %> spots are left!
        <% if @participants.include? current_user %>
          <% @registration = current_user.registrations.find_by(event_id: @event.id) %>
          <%= link_to "Can't go anymore?", event_registration_path(@event, @registration), method: :delete %>
        <% else %>
          <%= link_to "Join now", event_registrations_path(@event), method: :post %>
        <% end %>
        </p>
      </div>

      <h3> Event details </h3>

      <!-- Event organized by -->

      <p>
        <strong>Organized By:</strong>
        <%= link_to @event.organizer.first_name, @event.organizer %>
      </p>

      <!-- Event description -->

      <p>
        <strong>Description:</strong> <%= @event.description %>
      </p>

      <!-- Event location and tags -->

      <p>
        <strong>Location:</strong> <%= @event.address %>
      </p>

      <p>
      <strong>Tags:</strong>
      <%= @event.tags.join(', ') %>
      </p>

    <br>
    <br>

    <div class="fb-share-button" data-href="<%= event_url(@event) %>" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="">Share</a></div>

    <br>

    <% if current_user == @event.organizer %>
      <%= link_to "Copy This Event!", cool_form_path(1,{name: @event.name,
       organization: @event.organization,
       start_time: @event.start_time,
       end_time: @event.end_time,
       description: @event.description,
       address: @event.address,
       capacity: @event.capacity,
       tags: @event.tags,
       photos: @event.photos
     }), class: "btn btn-primary copy-event" %>
     <% end %>


    <!-- MAP PORTION OF PAGE -->
    <!-- The map will be drawn in this div -->
    <div id="map" style="width: 100% !important; height: 300px; margin: 50px 0px;"></div>
    <% content_for(:after_js) do %>
      <%= javascript_tag do %>
        $(document).ready(function() {
          var handler = Gmaps.build('Google');
          handler.buildMap({ internal: { id: 'map' } }, function() {
            markers = handler.addMarkers(<%= raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            if (markers.length == 0) {
              handler.getMap().setZoom(2);
            } else if (markers.length == 1) {
              handler.getMap().setZoom(14);
            }
          });
          $( '.swipebox' ).swipebox({
            useCSS : true, // false will force the use of jQuery for animations
            useSVG : true, // false to force the use of png for buttons
            initialIndexOnArray : 0, // which image index to init when a array is passed
            hideCloseButtonOnMobile : false, // true will hide the close button on mobile devices
            removeBarsOnMobile : true, // false will show top bar on mobile devices
            hideBarsDelay : 3000, // delay before hiding bars on desktop
            loopAtEnd: false // true will return to the first image after the last image is reached
          });
        });
      <% end %>
    <% end %>



</div>
</div>

<div class="footer">

      <% if @event.participants.include? current_user %>
      <div class="footer going">
      <% @registration = current_user.registrations.find_by(event_id: @event.id) %>
      <i class="fa fa-check" aria-hidden="true"></i>        You're going!
      </div>
      <%= link_to "Can't go anymore?", event_registration_path(@event, @registration), method: :delete %>
      <% elsif @event.organizer == current_user %>
      <div class="footer cancel-event">
      <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>  Cancel'.html_safe, event_path(@event), method: :delete %>
      <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>  Edit'.html_safe, cool_form_edit_path(@event.id, 1), class: 'cancel-event-edit' %>
      </div>
      <% else  %>
      <div class="footer question-going">
      <%= link_to 'I WANT TO JOIN', event_registrations_path(@event), method: :post, class: 'notice-going' %>
      </div>
      <% end %>

</div>

  </div>

app/views/events/users.html.erb
      <div class="center-middle-of-page">
        <div class="attendance-header">
          <% if @event.organizer == current_user %>
          <h2>Event Participants</h2>
            <h3>Review participants' attendance by marking the boxes below.</h3>
          <% else %>
          <h2>Event Participants</h2>
            <h3>Below are the participants for this event.</h3>
          <% end %>
        </div>

        <% @event.registrations.each do |reg| %>

        <%= link_to user_path(reg.participant) do %>
        <div class="attendance-card-container">
          <% if reg.participant.photo %>
          <%= cl_image_tag reg.participant.photo.path, width: 50, height: 50, crop: :fill, class: 'avatar-large attendance-avatar' %>
          <% else %>
          <%= image_tag('no-img.png', width: 50, height: 70, crop: :fill, class: 'avatar-large attendance-avatar') %>
          <% end %>
        <% end %>
          <div class="attendance-name">
            <%=  reg.participant.first_name %>
          </div>
          <!-- If current user is organizer and if event is past :  -->
          <% if policy(reg).update? %>
          <!-- If hasnt been updated yet:  -->
                <% if reg.incomplete? %>
                <%= link_to "NOT ATTENDED", event_registration_path(@event, reg), method: :put, class: "attendance-button-false" %>
                <% else %>
                <%= link_to "ATTENDED", event_registration_path(@event, reg), method: :put, class: "attendance-button-true" %>
                <% end %>
          <!-- TODO : redirect to same page with notice "thank you for your review" -->
          <% end %>
        </div>
        <% end %>
      </div>