config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  # Images implementation
  mount Attachinary::Engine => "/attachinary"

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'pages#home'

  devise_for :users, path_prefix: 'd', :controllers => { :registrations => :devise_registrations, omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:show]

  resources :events, except: [:index, :show]

  resources :events, only: [:show] do
    resources :registrations, only: [:create, :destroy, :update]
  end

  get '/events/', to: 'events#search', as: 'search'
  get '/save_data/', to: 'events#search'
  get '/events/:id/users/', to: 'events#users', as: 'event_users'
  get '/my_events/', to: 'events#my_events', as: 'user_events'
  get "/login_signup/", to: "pages#login_signup", as: "login_signup"
  get '/home_create/', to: 'pages#home_create', as: 'home_create'
  get '/home_search/', to: 'pages#home_search', as: 'home_search'

  get '/new/:number', to: "events#cool_form", as: 'cool_form'
  get '/events/:id/edit/:number', to: "events#cool_form_edit", as: 'cool_form_edit'


end

app/views/pages/home.html.erb
<div class="homepage-hero-module">

  <div class="video-container">
        <div class="filter"></div>
<!--         <video autoplay loop class="fillWidth">
            <source src="/videos/Everest/MP4/Everest.mp4" type="video/mp4" />Your browser does not support the video tag. I suggest you upgrade your browser.
            <source src="/videos/Everest/WEBM/Everest.webm" type="video/webm" />Your browser does not support the video tag. I suggest you upgrade your browser.
        </video> -->
        <video poster="img/yourposterimage.jpg" id="bgvid" playsinline autoplay muted loop>
<source src="https://player.vimeo.com/external/147585012.hd.mp4?s=1726e3b9f04d4351927b118333bc58008aeb2af7&profile_id=113" type="video/mp4"></video>
        <div class="poster hidden">
        <img src="/videos/Everest/Snapshots/Volunteasy.jpg" alt="">
        </div>
  </div>




<div class="container homepage homepage-hero-module">

  <div class="row">
    <div class="col-xs-12">

      <div class="row">
        <div class="col-xs-offset-1 col-xs-10">

          <div class="homepage-content">
            <div class="banner-content">
              <%= image_tag("Logo_green.png", class: 'logo-home') %>
              <h3 class="fat-title">
                The time to help is now
                </h3>

              <div class = "simple-form form-inline search-form">
                  <div class="form-group">
                <%= button_to "Find an event", home_search_path, class: "btn go btn-block home-margin-bottom", method: :get  %>

                <%= button_to "Create an event", home_create_path, class: "btn create btn-block", method: :get %>
                </div>

              </div>
            </div>
            <div class="create-login form-inline">
                <%= link_to "Log-in / Sign up", login_signup_path, class: 'login' %>

            </div>

          </div>

        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/home_create.html.erb
<div class="homepage-hero-module">

  <div class="video-container">
        <div class="filter"></div>
<!--         <video autoplay loop class="fillWidth">
            <source src="/videos/Everest/MP4/Everest.mp4" type="video/mp4" />Your browser does not support the video tag. I suggest you upgrade your browser.
            <source src="/videos/Everest/WEBM/Everest.webm" type="video/webm" />Your browser does not support the video tag. I suggest you upgrade your browser.
        </video> -->
        <video poster="img/yourposterimage.jpg" id="bgvid" playsinline autoplay muted loop>
<source src="https://player.vimeo.com/external/147585012.hd.mp4?s=1726e3b9f04d4351927b118333bc58008aeb2af7&profile_id=113" type="video/mp4"></video>
        <div class="poster hidden">
        <img src="/videos/Everest/Snapshots/Volunteasy.jpg" alt="">
        </div>
  </div>






<!-- IF PUSHED BUTTON CREATE EVENT :  -->



<div class="container homepage homepage-hero-module">

  <div class="row">
    <div class="col-xs-12">
        <div class="arrow">
            <%= link_to root_path do %>
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
            <% end %>
        </div>

      <div class="row">
        <div class="col-xs-offset-1 col-xs-10">

          <div class="homepage-content">
            <div class="banner-content">
              <%= image_tag("Logo_green.png", class: 'logo-home') %>

              <h3 class="fat-title">
                The time to help is now
                </h3>



<div class = "form-inline search-form">
                <%= simple_form_for @event, url: cool_form_path(1), html: { class: 'form-inline'}, method: :get do |f| %>

                <div class="icon-compass">
                <i class="fa fa-compass my-compass" aria-hidden="true"></i>

                <%= f.input :address, placeholder: 'Your city', label: false, input_html: {class: 'city home-margin-bottom', value: cookies[:address]} %>



                <%= f.button :submit, value: "Create!", class: "btn create btn-block signin", data: {disable_with: "Creating..."} %>
                </div>
                <% end %>





            </div>
            </div>

            <div class="col-xs-12 more_options">

            <%= link_to "More options", home_search_path, class: "" %>
            </div>


            <div class="create-login form-inline">
                <%= link_to "Log-in / Sign up", login_signup_path, class: 'login' %>

            </div>



        </div>
      </div>
    </div>
  </div>
</div>










</div>

app/views/pages/home_search.html.erb
<div class="homepage-hero-module">

  <div class="video-container">
        <div class="filter"></div>
<!--         <video autoplay loop class="fillWidth">
            <source src="/videos/Everest/MP4/Everest.mp4" type="video/mp4" />Your browser does not support the video tag. I suggest you upgrade your browser.
            <source src="/videos/Everest/WEBM/Everest.webm" type="video/webm" />Your browser does not support the video tag. I suggest you upgrade your browser.
        </video> -->
        <video poster="img/yourposterimage.jpg" id="bgvid" playsinline autoplay muted loop>
<source src="https://player.vimeo.com/external/147585012.hd.mp4?s=1726e3b9f04d4351927b118333bc58008aeb2af7&profile_id=113" type="video/mp4"></video>
        <div class="poster hidden">
        <img src="/videos/Everest/Snapshots/Volunteasy.jpg" alt="">
        </div>
  </div>






<!-- IF PUSHED BUTTON FIND AN EVENT : -->



<div class="container homepage homepage-hero-module">

  <div class="row">
    <div class="col-xs-12">
        <div class="arrow">
    <%= link_to root_path do %>
  <i class="fa fa-arrow-left" aria-hidden="true"></i>
<% end %>
</div>

      <div class="row">
        <div class="col-xs-offset-1 col-xs-10">

          <div class="homepage-content">
            <div class="banner-content">
              <%= image_tag("Logo_green.png", class: 'logo-home') %>

              <h3 class="fat-title">
                The time to help is now
                </h3>

              <div class = "form-inline search-form">
                <%= simple_form_for @event, url: search_path, html: { class: 'form-inline'}, method: :get do |f| %>

                <div class="icon-compass">
                <i class="fa fa-compass my-compass" aria-hidden="true"></i>

                <%= f.input :address, placeholder: 'Your city', label: false, input_html: {class: 'city home-margin-bottom', value: cookies[:address]} %>



                <%= f.button :submit, value: "Go!", class: "btn go btn-block signin", data: {disable_with: "Searching..."} %>
                </div>
                <% end %>


              </div>
            </div>
            <div class="col-xs-12 more_options">

            <%= link_to "More options", home_create_path, class: "" %>
            </div>
            <div class="create-login form-inline">
                <%= link_to "Log-in / Sign up", login_signup_path, class: 'login' %>

            </div>

          </div>

        </div>
      </div>
    </div>
  </div>
</div>




</div>

app/views/pages/login_signup.html.erb
<div class="homepage-hero-module">

  <div class="video-container">
        <div class="filter"></div>
<!--         <video autoplay loop class="fillWidth">
            <source src="/videos/Everest/MP4/Everest.mp4" type="video/mp4" />Your browser does not support the video tag. I suggest you upgrade your browser.
            <source src="/videos/Everest/WEBM/Everest.webm" type="video/webm" />Your browser does not support the video tag. I suggest you upgrade your browser.
        </video> -->
        <video poster="img/yourposterimage.jpg" id="bgvid" playsinline autoplay muted loop>
<source src="https://player.vimeo.com/external/147585012.hd.mp4?s=1726e3b9f04d4351927b118333bc58008aeb2af7&profile_id=113" type="video/mp4"></video>
        <div class="poster hidden">
        <img src="/videos/Everest/Snapshots/Volunteasy.jpg" alt="">
        </div>
  </div>






<div class="container homepage homepage-hero-module">



  <div class="row">
    <div class="col-xs-12">
    <div class="arrow">
    <%= link_to root_path do %>
  <i class="fa fa-arrow-left" aria-hidden="true"></i>
<% end %>
</div>
      <div class="row">
        <div class="col-xs-offset-1 col-xs-10">

          <div class="homepage-content">
            <div class="banner-content">
              <%= image_tag("Logo_green.png", class: 'logo-home') %>

              <h3 class="fat-title">
                The time to help is now
                </h3>

              <div class = "simple-form form-inline search-form">
                <div class="form-group">
                  <%= link_to "Log-in", new_user_session_path, class: "btn signin btn-block home-margin-bottom"  %>
                  <%= link_to "Sign up", new_user_registration_path, class: "btn signin btn-block"  %>
                </div>
              </div>
            </div>
            <div class="create-login form-inline">
                Registering you accept the Terms and Conditions and Privacy

            </div>

          </div>

        </div>
      </div>
    </div>
  </div>
</div>
</div>